name: Repo Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: arturmkr/calculator
          path: source-repo

      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: arturmkr/demo-package
          path: target-repo

      - name: Copy data
        run: |
          cp -r source-repo/* target-repo/mycalculator

#      - name: Push changes
#        run: |
#          cd target-repo
#          git config user.name "Your Name"
#          git config user.email "your-email@example.com"
#          git add .
#          git commit -m "Sync changes"

#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          repository: target-repo
#          commit_message: Some commit
#          push_options: --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: target-repo
          branch: update_data
          base: main
          delete-branch: true
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Update data'
          commit-message: Update cache
          labels: |
            automated pr
          body: |
            Updating data
          add-paths: |
            data.json