name: Repo Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Remove existing 'metrics' folder
        run: |
          rm -rf metrics

      - name: Clone remote repo into 'metrics' folder
        run: |
          git clone https://github.com/arturmkr/metrics metrics
          rm -rf metrics/.git
          rm -rf metrics/.github

      - name: Add __init__.py files
        run: |
          find metrics -type d -exec touch {}/__init__.py \;

      - name: Push changes
        run: |
          git config user.name "GitHub Action Repo Sync"
          git config user.email "no-reply@example.com"
          git status
          git add .
          git status
          git commit -m "Sync changes"
          git push